test/run.sh
test/viper/ok/private.tc.ok
test/viper/ok/private.vpr.stderr.ok
test/viper/ok/unsupported.tc.ok
test/viper/ok/unsupported.vpr.stderr.ok

The `moc --viper` command outputs generated Viper code to stdout and diagnostic messages to stderr.
* Prior to this change, test/run.sh used the `run` helper to produce .vpr files. The `run` helper always merges stdout and stderr, which results in ill-formed .vpr files if there are any diagnostic messages.
* Now test/run.sh has an additional helper `run_stderr` that keeps stdout and stderr separate. By using it instead of `run` we ensure that .vpr files are not contaminated with diagnostics.
Run `make -C test/viper` to confirm that this fixes broken Viper tests.
Note that `run_stderr` is a copy of `run` with minor tweaks, so this solution introduces some technical debt. A more principled approach would be to separate stdout and stderr in all commands (i.e. wholly replace `run` with …

Split stdout and stderr in viper/* tests

---

src/viper/pretty.ml
src/viper/syntax.ml
src/viper/trans.ml
test/repl/ok/viper.stdout.ok
test/viper/counter.mo
test/viper/ok/assertions.vpr.ok
test/viper/ok/async.vpr.ok
test/viper/ok/claim-broken.vpr.ok
test/viper/ok/claim-reward-naive.vpr.ok
test/viper/ok/claim-simple.vpr.ok
test/viper/ok/claim.vpr.ok
test/viper/ok/counter.silicon.ok
test/viper/ok/counter.vpr.ok
test/viper/ok/invariant.vpr.ok
test/viper/ok/simple-funs.silicon.ok
test/viper/ok/simple-funs.vpr.ok
test/viper/simple-funs.mo

Basic support for `Int` and `Bool` arguments and return values, incl. support for early return from a function.
The following example seems to work as expected:
`example.mo`
```
// @verify
actor Counter {
var count = 0 : Int;
public func increment() : async () {
count += 1;
};
public func getZero() : async Int {
if (true) {
return 0;
};
return 1;
};
public func getMax(n : Int) : async Int {
if (n > count) {
return n;
};
return count;
};
public func getCount() : async Int {
return count;
};
public func setCount(n : Int) : async () {
count := n;
};
};
```
It translates to the following Viper specification
`example.vpr`
```
define $Perm($Self) ((true && acc(($Self).count,write)))
define $Inv($Self) (true)
method __init__($Self: Ref)
requires $Perm($Self)
ensures $Perm($Self)
ensures …
```

motoko-san: arguments and return values

---

src/mo_def/arrange.ml
src/mo_def/syntax.ml
src/mo_frontend/assertions.mly
src/viper/pretty.ml
src/viper/trans.ml
test/fail/ok/verification-asserts.tc.ok
test/fail/verification-asserts.mo
test/viper/loop-invariant.mo
test/viper/ok/invariant.vpr.ok
test/viper/ok/loop-invariant.silicon.ok
test/viper/ok/loop-invariant.vpr.ok
test/viper/ok/simple-funs.vpr.ok

New features:
* invariants in while-loops
New test cases:
* test/viper/loop-invariant.mo
```
while (i < n) {
assert:loop:invariant (i * 2 == j);
assert:loop:invariant (j - i == i);
i := i + 1;
j := j + 2;
};
```

[DMS-22] motoko-san: loop invariants

---

default.nix

Tested locally, seems to work
```
$ nix-build --no-out-link
/nix/store/9x3vc2cv8pgjbxjm7bj785jiy2bm29r5-all-systems-go
/nix/store/hkr5phdyirqxvh5mbs28q1jsh8p188ag-base-doc
/nix/store/dvyb9zkkqxb8fw8cqa7z934cip7s88z1-base-src
/nix/store/iszz00c5jz6gpzbw689zw0c2l43hxva0-base-tests
/nix/store/masy6n95vhm63rxz123wsj4pin89m968-candid-tests
/nix/store/n68ly0c4p3wgsbk9rnfkrzxxzbs325jk-check-error-codes
/nix/store/vwarw7wa2nj7hg93wdb48hnjjrlrs4s9-check-formatting
/nix/store/saxijxm4jnhz6yvwaqkbwpsxnp47rfk1-check-generated
/nix/store/a404wn7q3y44nwyqxm6gg80j3f97617n-check-grammar
/nix/store/j3x3fmx0b959hl0rgkmqih109mzr4vgi-check-rts-formatting
/nix/store/1s6asj4pmq0ac8kab0lqlr8bwcmv9ry9-deser
/nix/store/c4lxl2q8svhnyvm77xxcw890fk5h8i40-didc
/nix/store/50cawwzwwp25zwc8kl45p7gfw2w57ahs-docs …
```

[DMS-31] motoko-san: enable viper tests

---

src/viper/prep.ml
src/viper/pretty.ml
src/viper/syntax.ml
src/viper/trans.ml
src/viper/traversals.ml
test/viper/ok/variants.silicon.ok
test/viper/ok/variants.vpr.ok
test/viper/variants.mo

New test case: `test/viper/variants.mo`

[DMS-12] Variant types

---

src/viper/README.md

Update the `README.md` to describe features implemented by Serokell for Milestone 1 and Milestone 2
**Milestone 1**
1. Arguments and return values
2. The `return` statement, early exit
3. Loop invariants
4. Method calls in `let`/`var` declarations, assignments
5. The `Nat` data type (translated to `Int`)
6. Arrays of primitive types
7. Monomorphisation of private methods (new pass: `prep.ml`)
8. Assertions on the result (the `var:return` syntax)
**Milestone 2**
1. Tuples of primitive types, matching on tuples in `let`
2. Option types
3. Variant types using the ADT Viper plugin (nominative typing, generics supported)
4. `switch` statements to match on tuples, options, variants

motoko-san: Update README.md

---

src/viper/trans.ml
test/viper/lits.mo
test/viper/ok/lits.silicon.ok
test/viper/ok/lits.tc.ok
test/viper/ok/lits.vpr.ok
test/viper/ok/lits.vpr.stderr.ok

Described literals and wildcard patterns in `switch` statements are translated in the next way:
* Wildcard pattern
```
case _ exp ==> if (true) exp
```
* Numeric/boolean literals
```
switch (n) {
case 42 exp
}
==>
if (n == 42) exp
```
```
switch (n) {
case true exp
}
==>
if (n == true) exp
```

[DMS-40] Support numeric, boolean literals and wildcards in switch patterns

---

test/viper/ok/reverse.tc.ok
test/viper/ok/reverse.vpr.ok
test/viper/ok/reverse.vpr.stderr.ok
test/viper/reverse.mo

* **Problem:** `await Reverse.reverse()` hangs (infinite loop)
* **Diagnosis:** `i` in copy_xarray wasn't being incremented
* **Solution:** add the increment, as well as assertions to ensure sufficient array access permissions

motoko-san: Fix a hang in reverse.mo

---

src/mo_frontend/typing.ml
src/mo_frontend/typing.mli
src/pipeline/pipeline.ml
src/pipeline/pipeline.mli
test/viper/ok/variants.tc.ok
test/viper/ok/variants.vpr.ok
test/viper/ok/variants.vpr.stderr.ok
test/viper/variants.mo

This change fixes the Viper translation of let-bound variants by removing normalization from `infer_exp` in `typing.ml`, thus making the nominal type accessible in `trans.ml`
I don't know all the implications of such a change, maybe we should make the new behavior conditional on the `--viper` flag?

[DMS-12] motoko-san: Let-bound variants

---

src/prelude/prim.mo
src/viper/common.ml
src/viper/pretty.ml
src/viper/syntax.ml
src/viper/trans.ml
test/fail/ok/no-timer-canc.tc.ok
test/fail/ok/no-timer-set.tc.ok
test/viper/odd-even.mo
test/viper/ok/odd-even.silicon.ok
test/viper/ok/odd-even.tc.ok
test/viper/ok/odd-even.vpr.ok
test/viper/ok/odd-even.vpr.stderr.ok
test/viper/ok/reverse.tc.ok
test/viper/ok/reverse.vpr.ok
test/viper/ok/reverse.vpr.stderr.ok
test/viper/reverse.mo

This PR adds two predicates for `motoko-san`: `forall` and `exists`. They could be used in assertions. Also, the `reverse.mo` example was updated.
```
assert Prim.forall<Nat>(func i = (0 <= i and i <= a.size()) implies a[i] == (old (a[i])));
===>
assume forall i : Int :: (0 <= i && i <= size(a)) ==> loc(a, i).int == old(loc(a, i).int);
```
The same goes for `exists`.
In translation, we check for function calls with the next scheme:
```
SomeModule.forall<T>(func ...)
```
If the user uses their own `forall` function then the translation could be incorrect.

[DMS-23] Support forall and exists

---

src/viper/prep.ml
src/viper/trans.ml

Turns out that `==` in OCaml is physical (pointer) equality, and is not guaranteed to work as a test for an empty list.

motoko-san: Stop using (==) in trans.ml and prep.ml

---

src/viper/common.ml
src/viper/trans.ml
test/viper/label-break-continue.mo
test/viper/ok/label-break-continue.silicon.ok
test/viper/ok/label-break-continue.tc.ok
test/viper/ok/label-break-continue.vpr.ok
test/viper/ok/label-break-continue.vpr.stderr.ok

`break <label>` and `continue <label>` statements are parsed into the `BreakE` node, so, supporting breaks means that we support continues.
The `LabelE` node could appear only next to the loops. `motoko`'s parser additionally wraps the loop's body with the label `continue <label_name>`. The final translation looks like this.
Motoko's pseudocode:
```
label while_loop while (cond) {
...
};
```
Parsed code:
```
(LabelE while_loop
(WhileE cond (LabelE "continue while_loop" exp))
)
```
Translated code:
```
while (cond) {
...
label $continue_while_loop
}
label $while_loop
```
`break`s in this case are translated into `goto`s.
`let v = label lbl : <typ> <exp>` case is translated to
```
var $t_lbl: <typ>;
<tr_exp>;
label $lbl;
v := $t_lbl;
```
where `<tr_expr>` is the translated expression with …

[DMS-39] Support labels, breaks, and continues

---

src/viper/pretty.ml
src/viper/trans.ml
test/viper/ok/reverse.vpr.ok

If an error occurs in the loop invariant the whole while loop would be highlighted.
This issue was fixed by adding an invariant to the source mapper (adding its location to `marks` array + surrounding the format string with `\017` and `\019`) and assigning the correct location to the invariant itself.

[DMS-41] Fix locations for while loop invariants

---

src/viper/trans.ml
test/viper/ok/reverse.tc.ok
test/viper/ok/reverse.vpr.ok
test/viper/ok/reverse.vpr.stderr.ok
test/viper/reverse.mo

In `dec_field'` in some places, we're passing the wrong context (e.g. `ctxt` instead of `ctxt'`). In this PR `ctxt` variables with ticks got stripped, let's use shadowing to get rid of this inconsistency.

[DMS-56] Pass the correct context in dec_field'

---

test/viper/ok/todo_record.vpr.ok
test/viper/todo_record.mo

* Strengthen actor invariant on `nextId`
* Strengthen `getTodo` specifiction

[DMS-60] enhance todo showcase

---

src/viper/pretty.ml
src/viper/trans.ml
test/viper/ok/array-of-tuples.vpr.ok
test/viper/ok/label-break-continue.vpr.ok
test/viper/ok/reverse.vpr.ok
test/viper/ok/todo_record.tc.ok
test/viper/ok/todo_record.vpr.ok
test/viper/ok/todo_record.vpr.stderr.ok
test/viper/ok/todo_tuple.vpr.ok

In this PR some miscellaneous fixes were applied:
* Fixed wrong `continue` translation in while loops.
* Added locations for pre/post conditions in the source mapper.
Previously, we were adding `continue` labels at the beginning of the `while` loop. This is not the correct translation because after `goto` the loop iteration check is skipped.
```
while (cond) {
label $lbl$continue$loop;
...
if (cond1) {
goto $lbl$continue$loop;
}
}
```
After going into `if (cond1)` `cond` check is skipped.
It's fixed by moving the `continue` label to the end of the loop.
```
while (cond) {
...
if (cond1) {
goto $lbl$continue$loop;
}
...
label $lbl$continue$loop;
}
```
We were lack of pre/post conditions locations in the source mapper. If the assertion contains an error the whole method body would be …

[DMS-60] Misc fixes

---

src/js/common.ml
src/js/moc_js.ml
src/pipeline/pipeline.ml
src/pipeline/pipeline.mli

Problem: When the language server loads a file, it goes through the process of typechecking all of its dependencies. We can be smarter about it and only load typecheck files that were invalidated.
Solution: Add `lsp_load_progs` that uses a cache to avoid doing excessive typechecking work. Change `chase_imports` (renamed to `chase_imports_cached`) to use the cache on valid files. Recreate `chase_imports` to use `chase_imports_cached` but ignoring the cache. Expose these changes in `parseMotokoTyped`. Create `parseMotokoWithDeps` that is like `parseMotoko` but also returns immediate dependencies.

[VSC-7] Implement a cache for typechecking

---

src/js/common.ml

Problem: We were asked during review to make scope cache optional.
Solution: Wrap the cache with `Js.Opt.t`. If falsy, use an empty map, if truthy, proceed as before.

[VSC-7] Make scopes cache optional

---

src/Makefile
src/mo_def/arrange.ml
src/mo_frontend/test_recovery.ml

Reason: precisely locate cursor in AST in the LSP server.
Original source: https://github.com/serokell/motoko/commit/870dc6e708b74786da23cfdcc0509b16a2e1a93f

serialize location of the ID

---

src/mo_def/arrange.ml
src/mo_frontend/typing.ml
src/pipeline/test_field_srcs.ml

Problem: We forgot to add sources for private fields. Also, turns out we don't need to serialize the type for DotE, only its left side.
Solution: In `object_of_scope`, also iterate private fields and add their sources. In `Arrange`, do not serialize the type for `DotE` nodes.

[VSC-10] Address latest points from review
